{{ if .Values.onPrem.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: ingressgateway-wc-certs
  namespace: {{ .Release.Namespace }}
data:
  tls.crt: |
    {{- $secret := lookup "v1" "Secret" .Values.onPrem.tlsNamespace .Values.onPrem.tlsSecret }}
    {{- if $secret }}
      {{- $tlsCrt := index $secret.data "tls.crt" }}
      {{- $tlsCrt | nindent 4 }}
    {{- else }}
      {{ fail "Secret not found: my-tls-secret" }}
    {{- end }}
{{ end }}
---
